default: &default
  adapter: postgresql
  encoding: 'UTF8'
  reconnect: true

development:
  <<: *default
  database: deputy_dev

test:
  <<: *default
  database: deputy_test

production:
  <<: *default
  database: deputy_prod
